name: rbt
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - matplotlib
  - pandas
  - jupyter
  - pip
  - pip:
      - nbconvert
      - plotly   # if any notebook uses it
