name: Build notebook figures
on:
  push:
    branches: [ "**" ]
    paths:
      - "notebooks/**"
      - "design/**"
      - "scripts/**"
      - ".github/workflows/build-figs.yml"
  pull_request:
    paths:
      - "notebooks/**"
      - "design/**"
      - "scripts/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo (LFS on)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Jupyter & libs
        run: |
          pip install --quiet jupyter nbconvert numpy scipy matplotlib pandas plotly

      # ---- NEW: make /scripts (and root) importable ----
      - name: Add repo root to PYTHONPATH
        run: |
          echo "PYTHONPATH=$GITHUB_WORKSPACE" >> "$GITHUB_ENV"

      - name: Install Inkscape
        run: |
          sudo apt-get update -y
          sudo apt-get install -y inkscape

      - name: Install repo in editable mode
        run: |
          pip install -e .

      - name: Generate tables & patch notebooks
        run: |
          python tools/bootstrap_notebooks.py
          python tools/write_figs.py
          python tools/generate_tables.py

      - name: Execute notebooks
        run: |
          set -e
          shopt -s nullglob
          for nb in notebooks/*.ipynb; do
            echo "▶ $nb"
            jupyter nbconvert --to notebook --execute "$nb" --inplace
          done

      - name: Export vector diagrams
        run: |
          inkscape --export-type=png design/axiom_flow.drawio  --export-filename=paper/figs/axiom_flow.png
          inkscape --export-type=png design/intro_timeline.drawio --export-filename=paper/figs/intro_timeline.png

      - name: Commit regenerated figures
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "CI: regenerate notebook figures & diagrams"
          file_pattern: |
            notebooks/*.ipynb
            paper/figs/*.png
