name: Build notebook figures
on:
  workflow_dispatch:          # run manually
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (LFS on)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: environment.yml      # <- uses the root file
          activate-environment: rbt
          auto-update-conda: true

      - name: Install Jupyter & Inkscape
        shell: bash -l {0}
        run: |
          pip install --quiet jupyter nbconvert
          sudo apt-get update -y
          sudo apt-get install -y inkscape

      - name: Execute notebooks
        shell: bash -l {0}
        run: |
          set -e
          shopt -s nullglob
          for nb in notebooks/*.ipynb; do
            echo "▶ $nb"
            jupyter nbconvert --execute --to notebook "$nb" --inplace
          done

      - name: Export vector diagrams
        shell: bash -l {0}
        run: |
          inkscape --export-type=pdf design/axiom_flow.drawio  --export-filename=paper/figs/axiom_flow.pdf
          inkscape --export-type=pdf design/number_tower.svg   --export-filename=paper/figs/number_tower.pdf
          inkscape --export-type=pdf design/tests_overview.svg --export-filename=paper/figs/tests_overview.pdf

      - name: Commit regenerated figures
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "CI: regenerate notebook figures & diagrams"
          file_pattern: |
            notebooks/*.ipynb
            paper/figs/*.pdf
